version: "3.8"

services:
    nginx:
        restart: always
        build:
            context: ./nginx
            # dockerfile: Dockerfile
        image: 171793/nginx
        container_name: nginx
        networks:
            - nodenet
        ports:
            - "8080:80"
        depends_on:
            - "db"
            - "node"

    node:
        restart: always
        command: npm start
        build:
            context: ./node
            # dockerfile: Dockerfile
        image: 171793/node
        container_name: node
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        ports:
            - "3000"
        networks:
            - nodenet
        # volumes:
        #   - ./node:/usr/src/app
        tty: true
        depends_on:
            - "db"

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - nodenet

networks:
    nodenet:
        name: nodenet
        driver: bridge